version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_DB: db
      PGDATABASE: db
      PGPASSWORD: ${POSTGRES_PASSWORD:-passwd}
      PGUSER: ${POSTGRES_USER:-postgres}
    ports:
      - 127.0.0.1:${LOCAL_DB_PORT:-15432}:5432

  

  backup:
    image: simple2b/pg-backup:1.0
    links:
      - db
    volumes:
      - ./backup:/backup
    environment:
      SCHEDULE_HOUR: ${SCHEDULE_HOUR:-0}
      SCHEDULE_MINUTE: ${SCHEDULE_MINUTE:-0}
      SCHEDULE_SECOND: ${SCHEDULE_SECOND:-0}
      POSTGRES_HOST: db
      POSTGRES_DATABASE: db
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-passwd}
      POSTGRES_EXTRA_OPTS: '--schema=public --blobs'
      DAYS_HISTORY: 30

  celery:
    image: simple2b/beam-suntory-app:latest
    restart: always
    env_file:
      - .env
    command: 'poetry run celery -A app.worker:celery_worker worker --loglevel=INFO'
    depends_on:
      - db
      - redis

  redis:
    image: redis:6.2-alpine
    restart: always
    env_file:
      - .env
    ports:
      - 127.0.0.1:${REDIS_PORT}:6379
    command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis:/data
  

volumes:
  db_data:
  redis:
    driver: local
