"""add notify marks

Revision ID: 0069a74a3e5e
Revises: d87c04071595
Create Date: 2024-05-28 15:02:03.332696

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0069a74a3e5e"
down_revision = "d87c04071595"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_notify_new_inventory",
                sa.Boolean(),
                nullable=False,
                server_default="true",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_notify_shipping",
                sa.Boolean(),
                nullable=False,
                server_default="true",
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_notify_request_share_status",
                sa.Boolean(),
                nullable=False,
                server_default="true",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_notify_request_share_status")
        batch_op.drop_column("is_notify_shipping")
        batch_op.drop_column("is_notify_new_inventory")

    # ### end Alembic commands ###
