"""add shelf life to allocate table

Revision ID: 03d9b3a41c8c
Revises: bbaac3252c56
Create Date: 2023-08-15 12:26:18.270006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "03d9b3a41c8c"
down_revision = "bbaac3252c56"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("io_allocate_product", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shelf_life_start", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("shelf_life_end", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("io_allocate_product", schema=None) as batch_op:
        batch_op.drop_column("shelf_life_end")
        batch_op.drop_column("shelf_life_start")

    # ### end Alembic commands ###
