"""delete warehouse from event

Revision ID: 04c377f0879f
Revises: ffd4b22f7e94
Create Date: 2023-09-05 17:22:35.989910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c377f0879f'
down_revision = 'ffd4b22f7e94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.Text(), nullable=False))
        batch_op.drop_constraint('fk_events_warehouse_id_warehouses', type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_events_warehouse_id_warehouses', 'warehouses', ['warehouse_id'], ['id'])
        batch_op.drop_column('comment')

    # ### end Alembic commands ###
