"""bulk_assign

Revision ID: 05c1a120b189
Revises: 751e538b9ad8
Create Date: 2024-10-21 06:38:48.720260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05c1a120b189'
down_revision = '751e538b9ad8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_assigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('absolute_file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_file_path', sa.String(length=512), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bulk_assigns_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_assigns'))
    )
    with op.batch_alter_table('assigns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bulk_assign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_assigns_bulk_assign_id_bulk_assigns'), 'bulk_assigns', ['bulk_assign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigns', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_assigns_bulk_assign_id_bulk_assigns'), type_='foreignkey')
        batch_op.drop_column('bulk_assign_id')

    op.drop_table('bulk_assigns')
    # ### end Alembic commands ###
