"""Billable

Revision ID: 06275271bc78
Revises: 05c1a120b189
Create Date: 2024-11-26 07:45:49.978775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06275271bc78'
down_revision = '05c1a120b189'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_billable_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_master_billable_groups')),
    sa.UniqueConstraint('name', name=op.f('uq_master_billable_groups_name'))
    )
    op.create_table('billable_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.Column('assigned_to', sa.String(length=32), nullable=True),
    sa.Column('master_billable_group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['master_billable_group_id'], ['master_billable_groups.id'], name=op.f('fk_billable_groups_master_billable_group_id_master_billable_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_billable_groups'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('billable_groups')
    op.drop_table('master_billable_groups')
    # ### end Alembic commands ###
