"""Add report events

Revision ID: 097bd74c95f9
Revises: 4a921e625966
Create Date: 2023-09-14 15:40:25.242566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '097bd74c95f9'
down_revision = '4a921e625966'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_report_events_event_id_events')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('date_reserve_from')
        batch_op.drop_column('date_reserve_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_reserve_to', sa.DATE(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('date_reserve_from', sa.DATE(), autoincrement=False, nullable=True))

    op.drop_table('report_events')
    # ### end Alembic commands ###
