"""report inbound order

Revision ID: 0ac5eb806d00
Revises: cd4f28bfe83f
Create Date: 2023-09-27 14:45:36.090227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ac5eb806d00'
down_revision = 'cd4f28bfe83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_inbound_orders',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('inbound_order_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=True),
    sa.Column('history', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_orders.id'], name=op.f('fk_report_inbound_orders_inbound_order_id_inbound_orders')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_report_inbound_orders_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_inbound_orders'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_inbound_orders')
    # ### end Alembic commands ###
