"""assign_uuid

Revision ID: 0d3355bf4039
Revises: d01b6d8a40df
Create Date: 2024-02-29 09:46:51.418602

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0d3355bf4039"
down_revision = "d01b6d8a40df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("uuid", sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.drop_column("uuid")

    # ### end Alembic commands ###
