"""ship_request_id to cart

Revision ID: 160fab5d3ecd
Revises: f5a7ae3c708c
Create Date: 2023-07-27 16:57:03.855915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "160fab5d3ecd"
down_revision = "f5a7ae3c708c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("ship_request_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_carts_ship_request_id_ship_requests"),
            "ship_requests",
            ["ship_request_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_carts_ship_request_id_ship_requests"), type_="foreignkey"
        )
        batch_op.drop_column("ship_request_id")

    # ### end Alembic commands ###
