"""Rename allocated product table

Revision ID: 17a0288bd761
Revises: 2e56812e75e6
Create Date: 2023-09-04 14:50:53.771843

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17a0288bd761'
down_revision = '2e56812e75e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products_allocated',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('inbound_order_id', sa.Integer(), nullable=False),
    sa.Column('shelf_life_start', sa.Date(), nullable=False),
    sa.Column('shelf_life_end', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_orders.id'], name=op.f('fk_products_allocated_inbound_order_id_inbound_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_products_allocated_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products_allocated'))
    )
    op.drop_table('io_allocate_product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('io_allocate_product',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('inbound_order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shelf_life_start', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('shelf_life_end', sa.DATE(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['inbound_order_id'], ['inbound_orders.id'], name='fk_io_allocate_product_inbound_order_id_inbound_orders', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_io_allocate_product_product_id_products', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_io_allocate_product')
    )
    op.drop_table('products_allocated')
    # ### end Alembic commands ###
