"""report inventory to warehouse product

Revision ID: 1be1a122b990
Revises: e8614135c5ff
Create Date: 2023-09-25 12:44:50.107687

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1be1a122b990"
down_revision = "e8614135c5ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("warehouse_product_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_report_inventories_warehouse_product_id_warehouse_product"),
            "warehouse_product",
            ["warehouse_product_id"],
            ["id"],
        )

    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_warehouse_product_report_inventory_id_report_inventories",
            type_="foreignkey",
        )
        batch_op.drop_column("report_inventory_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "report_inventory_id", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.create_foreign_key(
            "fk_warehouse_product_report_inventory_id_report_inventories",
            "report_inventories",
            ["report_inventory_id"],
            ["id"],
        )

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_report_inventories_warehouse_product_id_warehouse_product"),
            type_="foreignkey",
        )
        batch_op.drop_column("warehouse_product_id")

    # ### end Alembic commands ###
