"""add proof_of_delivery and tracking

Revision ID: 1dd1cfbba463
Revises: 75dc5ab39f38
Create Date: 2024-03-27 11:16:46.118976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dd1cfbba463'
down_revision = '75dc5ab39f38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_of_delivery', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tracking', sa.Text(), nullable=True))

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('proof_of_delivery', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tracking', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.drop_column('tracking')
        batch_op.drop_column('proof_of_delivery')

    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.drop_column('tracking')
        batch_op.drop_column('proof_of_delivery')

    # ### end Alembic commands ###
