"""add order numb to share request

Revision ID: 20bd2dd3dab1
Revises: 12adaec72d3b
Create Date: 2023-08-23 11:00:29.932706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "20bd2dd3dab1"
down_revision = "12adaec72d3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("order_numb", sa.String(length=64), nullable=True)
        )
        batch_op.create_unique_constraint(
            batch_op.f("uq_request_share_order_numb"), ["order_numb"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("uq_request_share_order_numb"), type_="unique"
        )
        batch_op.drop_column("order_numb")

    # ### end Alembic commands ###
