"""correct groups for io

Revision ID: 2186890a61e1
Revises: 76526150a845
Create Date: 2023-08-03 11:47:51.865057

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "2186890a61e1"
down_revision = "76526150a845"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_product_quantity_group_group_id_groups", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_product_quantity_group_group_id_groups_for_product"),
            "groups_for_product",
            ["group_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_product_quantity_group_group_id_groups_for_product"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_product_quantity_group_group_id_groups", "groups", ["group_id"], ["id"]
        )

    # ### end Alembic commands ###
