"""remove delivery agent from io

Revision ID: 21e6ebb8daa3
Revises: 3ba0b6284cfa
Create Date: 2023-08-14 10:32:36.449895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "21e6ebb8daa3"
down_revision = "3ba0b6284cfa"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_inbound_orders_delivery_agent_id_delivery_agents", type_="foreignkey"
        )
        batch_op.drop_column("delivery_agent_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "delivery_agent_id", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.create_foreign_key(
            "fk_inbound_orders_delivery_agent_id_delivery_agents",
            "delivery_agents",
            ["delivery_agent_id"],
            ["id"],
        )

    # ### end Alembic commands ###
