"""report inbound order

Revision ID: 2bfaefa934ed
Revises: 5724781621b3
Create Date: 2023-09-26 14:40:22.927554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2bfaefa934ed"
down_revision = "5724781621b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_inbound_orders",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("inbound_order_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("history", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inbound_order_id"],
            ["inbound_orders.id"],
            name=op.f("fk_report_inbound_orders_inbound_order_id_inbound_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_inbound_orders_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_inbound_orders")),
    )
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=64), nullable=True
        )
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "type", existing_type=sa.VARCHAR(length=64), nullable=True
        )
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )

    op.drop_table("report_inbound_orders")
    # ### end Alembic commands ###
