"""change type of status division

Revision ID: 2c81e116b71c
Revises: cef2e6ffcec6
Create Date: 2023-08-01 10:21:37.015592

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2c81e116b71c"
down_revision = "cef2e6ffcec6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("divisions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("activated", sa.Boolean(), nullable=True))
        batch_op.drop_column("status")

    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.alter_column("manager_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.alter_column("manager_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("divisions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "status", sa.VARCHAR(length=64), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_column("activated")

    # ### end Alembic commands ###
