"""add request-share-user

Revision ID: 2cb65e4339a6
Revises: 81bb0389bc64
Create Date: 2023-08-02 12:46:44.282888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb65e4339a6'
down_revision = '81bb0389bc64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_share_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_share_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['request_share_id'], ['request_share.id'], name=op.f('fk_request_share_user_request_share_id_request_share')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_request_share_user_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_request_share_user'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('request_share_user')
    # ### end Alembic commands ###
