"""active_time to str

Revision ID: 2fdb5d451d77
Revises: 40fb1db5ca2a
Create Date: 2023-07-19 16:12:29.617837

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2fdb5d451d77"
down_revision = "40fb1db5ca2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.alter_column(
            "active_time",
            existing_type=postgresql.TIMESTAMP(),
            type_=sa.String(length=64),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.alter_column(
            "active_time",
            existing_type=sa.String(length=64),
            type_=postgresql.TIMESTAMP(),
        )

    # ### end Alembic commands ###
