"""product name to str 128 and unique name

Revision ID: 307d8f87cd33
Revises: 20bd2dd3dab1
Create Date: 2023-08-23 12:37:02.524091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "307d8f87cd33"
down_revision = "20bd2dd3dab1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=64),
            type_=sa.String(length=128),
            existing_nullable=False,
        )
        batch_op.create_unique_constraint(batch_op.f("uq_products_name"), ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_products_name"), type_="unique")
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=128),
            type_=sa.VARCHAR(length=64),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
