"""Report shipping

Revision ID: 319a6abd775c
Revises: 9f27cfb15648
Create Date: 2023-09-28 18:29:40.093232

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '319a6abd775c'
down_revision = '9f27cfb15648'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_shipping',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ship_request_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('history', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_request_id'], ['ship_requests.id'], name=op.f('fk_reports_shipping_ship_request_id_ship_requests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_shipping_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports_shipping'))
    )
    with op.batch_alter_table('adjusts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('adjusts_group_qty', schema=None) as batch_op:
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_after',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('quantity_before',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('report_inbound_orders', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('inbound_order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('history',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.alter_column('order_numb',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)
        batch_op.drop_constraint('uq_ship_requests_order_numb', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_ship_requests_order_numb', ['order_numb'])
        batch_op.alter_column('order_numb',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)

    with op.batch_alter_table('report_inbound_orders', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('history',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
        batch_op.alter_column('type',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('inbound_order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('adjusts_group_qty', schema=None) as batch_op:
        batch_op.alter_column('quantity_before',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('quantity_after',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('product_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('adjusts', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('reports_shipping')
    # ### end Alembic commands ###
