"""remove sub_brand and stock status

Revision ID: 33dffcf321b3
Revises: 7b0bcdf3557f
Create Date: 2023-06-30 17:43:21.357889

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33dffcf321b3'
down_revision = '7b0bcdf3557f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('fk_products_sub_brand_id_str_values', type_='foreignkey')
        batch_op.drop_column('sub_brand_id')
        batch_op.drop_column('stock_status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_status', postgresql.ENUM('IN_STOCK', 'LOW_STOCK', 'OUT_OF_STOCK', name='stockstatus'), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('sub_brand_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_products_sub_brand_id_str_values', 'str_values', ['sub_brand_id'], ['id'])

    # ### end Alembic commands ###
