"""product_groups

Revision ID: 345c8e9c64c1
Revises: b47e674a5adb
Create Date: 2023-07-04 22:59:34.496534

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "345c8e9c64c1"
down_revision = "b47e674a5adb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product_group",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_product_group_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_product_group_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_group")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product_group")
    # ### end Alembic commands ###
