"""group_for_product for warehouse

Revision ID: 35654be2abe6
Revises: 2186890a61e1
Create Date: 2023-08-03 12:22:16.757918

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "35654be2abe6"
down_revision = "2186890a61e1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_warehouse_product_group_id_groups", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_warehouse_product_group_id_groups_for_product"),
            "groups_for_product",
            ["group_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_warehouse_product_group_id_groups_for_product"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_warehouse_product_group_id_groups", "groups", ["group_id"], ["id"]
        )

    # ### end Alembic commands ###
