"""remove premises

Revision ID: 36d4ddd0b591
Revises: 75b505a21e96
Create Date: 2023-07-14 15:31:29.917273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36d4ddd0b591'
down_revision = '75b505a21e96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('premises')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premises', postgresql.ENUM('ON_PREMISE', 'OFF_PREMISE', name='premises'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
