"""remove str_values foreign key from supplier

Revision ID: 36de042a359a
Revises: 82efab85f727
Create Date: 2023-07-11 11:32:54.370031

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "36de042a359a"
down_revision = "82efab85f727"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_suppliers_region_id_str_values", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_suppliers_country_id_str_values", type_="foreignkey"
        )
        batch_op.drop_column("country_id")
        batch_op.drop_column("region_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("region_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("country_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_suppliers_country_id_str_values", "str_values", ["country_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_suppliers_region_id_str_values", "str_values", ["region_id"], ["id"]
        )

    # ### end Alembic commands ###
