"""billiable_group assigns

Revision ID: 389030ed9b77
Revises: 06275271bc78
Create Date: 2024-11-26 09:09:31.688336

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389030ed9b77'
down_revision = '06275271bc78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billable_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to_inbound', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('assigned_to_outbound', sa.Boolean(), nullable=False))
        batch_op.drop_column('assigned_to')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billable_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_to', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
        batch_op.drop_column('assigned_to_outbound')
        batch_op.drop_column('assigned_to_inbound')

    # ### end Alembic commands ###
