"""supplier to product, groups instead fixed columns

Revision ID: 38a23d99abad
Revises: 345c8e9c64c1
Create Date: 2023-07-05 15:18:41.037420

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "38a23d99abad"
down_revision = "345c8e9c64c1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("supplier_id", sa.Integer()))
        batch_op.drop_constraint(
            "fk_products_language_id_str_values", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_products_category_id_product_categories", type_="foreignkey"
        )
        batch_op.drop_constraint("fk_products_brand_id_str_values", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_products_supplier_id_suppliers"),
            "suppliers",
            ["supplier_id"],
            ["id"],
        )
        batch_op.drop_column("brand_id")
        batch_op.drop_column("language_id")
        batch_op.drop_column("category_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("category_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("language_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("brand_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.drop_constraint(
            batch_op.f("fk_products_supplier_id_suppliers"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_products_brand_id_str_values", "str_values", ["brand_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_products_category_id_product_categories",
            "product_categories",
            ["category_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_products_language_id_str_values", "str_values", ["language_id"], ["id"]
        )
        batch_op.drop_column("supplier_id")

    # ### end Alembic commands ###
