"""add favorite-store-user

Revision ID: 3a1d4b6d3019
Revises: 6b0253af8b1a
Create Date: 2023-07-25 18:03:12.308653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3a1d4b6d3019"
down_revision = "6b0253af8b1a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "favorite_store_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("store_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_favorite_store_user_store_id_stores"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_favorite_store_user_user_id_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_favorite_store_user")),
    )
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "comment",
            existing_type=sa.VARCHAR(length=256),
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "comment", existing_type=sa.VARCHAR(length=256), nullable=True
        )

    op.drop_table("favorite_store_user")
    # ### end Alembic commands ###
