"""report id nullable True

Revision ID: 3d2e74f022b9
Revises: a82982d1dc28
Create Date: 2023-09-18 16:40:52.592628

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3d2e74f022b9"
down_revision = "a82982d1dc28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("report_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("report_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
