"""products to reports

Revision ID: 3e28c5a81750
Revises: 1be1a122b990
Create Date: 2023-09-25 17:07:59.798249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3e28c5a81750"
down_revision = "1be1a122b990"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.add_column(sa.Column("product_id", sa.Integer(), nullable=False))
        batch_op.drop_constraint(
            "fk_report_inventories_warehouse_product_id_warehouse_product",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_report_inventories_product_id_products"),
            "products",
            ["product_id"],
            ["id"],
        )
        batch_op.drop_column("warehouse_product_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "warehouse_product_id",
                sa.INTEGER(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_report_inventories_product_id_products"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_report_inventories_warehouse_product_id_warehouse_product",
            "warehouse_product",
            ["warehouse_product_id"],
            ["id"],
        )
        batch_op.drop_column("product_id")

    # ### end Alembic commands ###
