"""store category foreign key for store

Revision ID: 42985b8f3ed2
Revises: 8fbe5fa077b2
Create Date: 2023-08-04 14:21:27.669113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "42985b8f3ed2"
down_revision = "8fbe5fa077b2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_category_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint("uq_stores_store_category", type_="unique")
        batch_op.create_foreign_key(
            batch_op.f("fk_stores_store_category_id_store_categories"),
            "store_categories",
            ["store_category_id"],
            ["id"],
        )
        batch_op.drop_column("store_category")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("stores", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "store_category",
                sa.VARCHAR(length=64),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_stores_store_category_id_store_categories"),
            type_="foreignkey",
        )
        batch_op.create_unique_constraint(
            "uq_stores_store_category", ["store_category"]
        )
        batch_op.drop_column("store_category_id")

    # ### end Alembic commands ###
