"""unrequired fields for product

Revision ID: 453643ac6064
Revises: 88e0268dc5fd
Create Date: 2023-08-16 15:28:57.075352

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "453643ac6064"
down_revision = "88e0268dc5fd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column("supplier_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "currency",
            existing_type=postgresql.ENUM("USD", "CAD", name="currency"),
            nullable=True,
        )
        batch_op.alter_column(
            "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "low_stock_level", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("program_year", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column("package_qty", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "numb_of_items_per_case", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "numb_of_cases_per_outer_case", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "comments", existing_type=sa.VARCHAR(length=128), nullable=True
        )
        batch_op.alter_column(
            "weight", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "length", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "width", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.alter_column(
            "height", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=True
        )
        batch_op.drop_column("product_type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "product_type",
                postgresql.ENUM(
                    "SIMPLE_PRODUCT", "VARIABLE_PRODUCT", name="producttype"
                ),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.alter_column(
            "height", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "width", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "length", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "weight", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "comments", existing_type=sa.VARCHAR(length=128), nullable=False
        )
        batch_op.alter_column(
            "numb_of_cases_per_outer_case", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "numb_of_items_per_case", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column("package_qty", existing_type=sa.INTEGER(), nullable=False)
        batch_op.alter_column(
            "program_year", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "low_stock_level", existing_type=sa.INTEGER(), nullable=False
        )
        batch_op.alter_column(
            "price", existing_type=sa.DOUBLE_PRECISION(precision=53), nullable=False
        )
        batch_op.alter_column(
            "currency",
            existing_type=postgresql.ENUM("USD", "CAD", name="currency"),
            nullable=False,
        )
        batch_op.alter_column("supplier_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
