"""group, approval permission to user

Revision ID: 460321884c7d
Revises: a0feb85eef9f
Create Date: 2023-06-27 17:45:05.036355

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '460321884c7d'
down_revision = 'a0feb85eef9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('approval_permission', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('approval_permission')
        batch_op.drop_column('group')

    # ### end Alembic commands ###
