"""report_events, ship_requests, pass cards

Revision ID: 479bf4cc0532
Revises: 1dc49d36f078
Create Date: 2023-09-21 15:47:05.539678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "479bf4cc0532"
down_revision = "1dc49d36f078"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_events_report_id_report_events", type_="foreignkey"
        )
        batch_op.drop_column("report_id")

    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("report_event_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_ship_requests_report_event_id_report_events"),
            "report_events",
            ["report_event_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_ship_requests_report_event_id_report_events"),
            type_="foreignkey",
        )
        batch_op.drop_column("report_event_id")

    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_events_report_id_report_events", "report_events", ["report_id"], ["id"]
        )

    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
