"""remove premises

Revision ID: 492825d1dcd5
Revises: 36de042a359a
Create Date: 2023-07-13 12:38:49.032737

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '492825d1dcd5'
down_revision = '36de042a359a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('premises')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('premises', postgresql.ENUM('ON_PREMISE', 'OFF_PREMISE', name='premises'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
