"""added reserve date to event

Revision ID: 4a921e625966
Revises: cea2e3a205eb
Create Date: 2023-09-14 14:19:45.294440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a921e625966'
down_revision = 'cea2e3a205eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_reserve_from', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_reserve_to', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_column('date_reserve_to')
        batch_op.drop_column('date_reserve_from')

    # ### end Alembic commands ###
