"""assign to report_assign

Revision ID: 5724781621b3
Revises: 479bf4cc0532
Create Date: 2023-09-22 15:37:03.520742

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5724781621b3"
down_revision = "479bf4cc0532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("type", sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_assigns_user_id_users"), "users", ["user_id"], ["id"]
        )

    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_assigns_user_id_users"), type_="foreignkey"
        )
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.drop_column("user_id")
        batch_op.drop_column("type")

    # ### end Alembic commands ###
