"""add incoome stock notify

Revision ID: 576120fad5b3
Revises: b7d195d3cad9
Create Date: 2024-09-26 09:25:25.949198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '576120fad5b3'
down_revision = 'b7d195d3cad9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incoming_stock_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('approx_arrival_date', sa.DateTime(), nullable=False),
    sa.Column('recived_date', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_incoming_stock_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incoming_stock_notifications'))
    )
    op.create_table('incoming_stock_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=64), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('stock_notify_id', sa.Integer(), nullable=False),
    sa.Column('product_info', sa.String(length=256), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_incoming_stock_products_product_id_products')),
    sa.ForeignKeyConstraint(['stock_notify_id'], ['incoming_stock_notifications.id'], name=op.f('fk_incoming_stock_products_stock_notify_id_incoming_stock_notifications')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_incoming_stock_products'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incoming_stock_products')
    op.drop_table('incoming_stock_notifications')
    # ### end Alembic commands ###
