"""inbound order and store edits

Revision ID: 5782caeb6cbe
Revises: b6adac617374
Create Date: 2023-07-20 10:17:21.635870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5782caeb6cbe'
down_revision = 'b6adac617374'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_title', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('delivery_date', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('status', sa.String(length=64), nullable=False))
        batch_op.alter_column('active_time',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.drop_column('item_type')

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('region', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('fk_stores_country_id_str_values', type_='foreignkey')
        batch_op.drop_constraint('fk_stores_region_id_str_values', type_='foreignkey')
        batch_op.drop_column('country_id')
        batch_op.drop_column('region_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_stores_region_id_str_values', 'str_values', ['region_id'], ['id'])
        batch_op.create_foreign_key('fk_stores_country_id_str_values', 'str_values', ['country_id'], ['id'])
        batch_op.drop_column('region')
        batch_op.drop_column('country')

    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_type', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
        batch_op.alter_column('active_time',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
        batch_op.drop_column('status')
        batch_op.drop_column('delivery_date')
        batch_op.drop_column('order_title')

    # ### end Alembic commands ###
