"""cart change  group format data

Revision ID: 6278e53df31e
Revises: ad231b84dcd3
Create Date: 2023-09-29 10:59:06.752999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6278e53df31e"
down_revision = "ad231b84dcd3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_carts_group_id_groups"), "groups", ["group_id"], ["id"]
        )
        batch_op.drop_column("group")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "group", sa.VARCHAR(length=64), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_carts_group_id_groups"), type_="foreignkey"
        )
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
