"""ReportEvent -> ShipRequets one to many

Revision ID: 63f78a2f43a8
Revises: df475b67cfe5
Create Date: 2023-10-04 15:12:46.367758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f78a2f43a8'
down_revision = 'df475b67cfe5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_request_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_report_events_ship_request_id_ship_requests'), 'ship_requests', ['ship_request_id'], ['id'])

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ship_requests_report_event_id_report_events', type_='foreignkey')
        batch_op.drop_column('report_event_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_event_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_ship_requests_report_event_id_report_events', 'report_events', ['report_event_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('report_events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_report_events_ship_request_id_ship_requests'), type_='foreignkey')
        batch_op.drop_column('ship_request_id')

    # ### end Alembic commands ###
