"""division added

Revision ID: 643909f6d74a
Revises: 86c602aa44db
Create Date: 2023-07-31 14:55:31.018151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "643909f6d74a"
down_revision = "86c602aa44db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "divisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("parent_role", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_divisions")),
        sa.UniqueConstraint("name", name=op.f("uq_divisions_name")),
    )
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.alter_column(
            "inbound_order_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("division", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_users_division_divisions"), "divisions", ["division"], ["id"]
        )

    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.alter_column("group_id", existing_type=sa.INTEGER(), nullable=False)

    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.alter_column("manager_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.alter_column("manager_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.alter_column("group_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_users_division_divisions"), type_="foreignkey"
        )
        batch_op.drop_column("division")

    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.alter_column(
            "inbound_order_id", existing_type=sa.INTEGER(), nullable=True
        )

    op.drop_table("divisions")
    # ### end Alembic commands ###
