"""added store_category to ship ship_request

Revision ID: 64a365f824b3
Revises: afa81825eff5
Create Date: 2023-07-17 15:41:11.568275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64a365f824b3'
down_revision = 'afa81825eff5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_category', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.drop_column('store_category')

    # ### end Alembic commands ###
