"""shelf_life from product to imbound order

Revision ID: 66cfff41d043
Revises: dc061e0b3e6f
Create Date: 2023-08-11 15:16:15.146116

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "66cfff41d043"
down_revision = "dc061e0b3e6f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("shelf_life_start", sa.DateTime(), nullable=False)
        )
        batch_op.add_column(sa.Column("shelf_life_end", sa.DateTime(), nullable=False))

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("shelf_life_end")
        batch_op.drop_column("shelf_life_start")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "shelf_life_start",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "shelf_life_end",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=False,
            )
        )

    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.drop_column("shelf_life_end")
        batch_op.drop_column("shelf_life_start")

    # ### end Alembic commands ###
