"""product name to str 256 and descrition to 512

Revision ID: 6740fcf55222
Revises: 65f05d8db5e6
Create Date: 2023-08-23 15:15:59.304423

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6740fcf55222"
down_revision = "65f05d8db5e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.String(length=512),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "comments",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.alter_column(
            "comments",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=True,
        )
        batch_op.alter_column(
            "description",
            existing_type=sa.String(length=512),
            type_=sa.VARCHAR(length=256),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
