"""added product_quantity_group

Revision ID: 6b0253af8b1a
Revises: d9389bd518f4
Create Date: 2023-07-25 12:54:49.313596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0253af8b1a'
down_revision = 'd9389bd518f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_quantity_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_product_quantity_group_group_id_groups')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_quantity_group_product_id_products')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_product_quantity_group_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_quantity_group'))
    )
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=256))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.alter_column('comment',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)

    op.drop_table('product_quantity_group')
    # ### end Alembic commands ###
