"""Add Report request share

Revision ID: 6b6fd5ff00f2
Revises: 479bf4cc0532
Create Date: 2023-09-22 17:01:34.757341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6fd5ff00f2'
down_revision = '479bf4cc0532'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reports_request_share',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('request_share_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('history', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['request_share_id'], ['request_share.id'], name=op.f('fk_reports_request_share_request_share_id_request_share')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_reports_request_share_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reports_request_share'))
    )
    with op.batch_alter_table('assigns', schema=None) as batch_op:
        batch_op.alter_column('from_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('order_numb',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=36),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.alter_column('order_numb',
               existing_type=sa.String(length=36),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assigns', schema=None) as batch_op:
        batch_op.alter_column('from_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('reports_request_share')
    # ### end Alembic commands ###
