"""delete full_name in user

Revision ID: 6de366a1c32e
Revises: afa3bb1fe9f7
Create Date: 2023-06-28 14:31:40.677162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6de366a1c32e'
down_revision = 'afa3bb1fe9f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
