"""add adjust

Revision ID: 70be3f9700a9
Revises: 901749b97d51
Create Date: 2023-08-29 09:19:21.390689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70be3f9700a9'
down_revision = '901749b97d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adjusts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_adjusts_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjusts'))
    )
    op.create_table('adjusts_group_qty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('adjust_id', sa.Integer(), nullable=False),
    sa.Column('warehouse_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adjust_id'], ['adjusts.id'], name=op.f('fk_adjusts_group_qty_adjust_id_adjusts')),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], name=op.f('fk_adjusts_group_qty_group_id_groups')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], name=op.f('fk_adjusts_group_qty_warehouse_id_warehouses')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_adjusts_group_qty'))
    )
    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.alter_column('order_numb',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.alter_column('order_numb',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)

    op.drop_table('adjusts_group_qty')
    op.drop_table('adjusts')
    # ### end Alembic commands ###
