"""shelf life from product to io

Revision ID: 70d161a84c71
Revises: 42985b8f3ed2
Create Date: 2023-08-04 15:58:52.856594

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "70d161a84c71"
down_revision = "42985b8f3ed2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.add_column(sa.Column("shelf_life_start", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("shelf_life_end", sa.DateTime(), nullable=True))

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("shelf_life_start")
        batch_op.drop_column("shelf_life_end")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "shelf_life_end",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "shelf_life_start",
                postgresql.TIMESTAMP(),
                autoincrement=False,
                nullable=True,
            )
        )

    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.drop_column("shelf_life_end")
        batch_op.drop_column("shelf_life_start")

    # ### end Alembic commands ###
