"""created_at for warehouse_product

Revision ID: 71314055728b
Revises: 47b50647a3cb
Create Date: 2023-10-24 12:24:42.197566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71314055728b'
down_revision = '47b50647a3cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouse_product', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
