"""add bulk ship

Revision ID: 751e538b9ad8
Revises: 0891c3be73b4
Create Date: 2024-10-16 10:10:51.259870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751e538b9ad8'
down_revision = '0891c3be73b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_ships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('absolute_file_path', sa.String(length=512), nullable=False),
    sa.Column('uploaded_file_path', sa.String(length=512), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_bulk_ships_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_ships'))
    )
    with op.batch_alter_table('bulk_ships', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bulk_ships_uuid'), ['uuid'], unique=False)

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint('fk_carts_from_warehouse_product_id_warehouse_product', type_='foreignkey')
        batch_op.drop_column('from_warehouse_product_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_access_bulk_ship', sa.Boolean(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('has_access_bulk_assign', sa.Boolean(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('has_access_bulk_assign')
        batch_op.drop_column('has_access_bulk_ship')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_warehouse_product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_carts_from_warehouse_product_id_warehouse_product', 'warehouse_product', ['from_warehouse_product_id'], ['id'])

    with op.batch_alter_table('bulk_ships', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bulk_ships_uuid'))

    op.drop_table('bulk_ships')
    # ### end Alembic commands ###
