"""set product name not uqique

Revision ID: 75dc5ab39f38
Revises: 9558c148eb4a
Create Date: 2024-03-14 11:15:14.582875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75dc5ab39f38'
down_revision = '9558c148eb4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_products_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_products_name', ['name'])

    # ### end Alembic commands ###
