"""share from group

Revision ID: 76526150a845
Revises: e5ae3950b1a2
Create Date: 2023-08-03 11:22:41.347229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "76526150a845"
down_revision = "e5ae3950b1a2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.add_column(sa.Column("from_group_id", sa.Integer(), nullable=True))
        batch_op.drop_constraint("fk_request_share_group_id_groups", type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_request_share_from_group_id_groups_for_product"),
            "groups_for_product",
            ["from_group_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_request_share_group_id_groups_for_product"),
            "groups_for_product",
            ["group_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_request_share_group_id_groups_for_product"),
            type_="foreignkey",
        )
        batch_op.drop_constraint(
            batch_op.f("fk_request_share_from_group_id_groups_for_product"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_request_share_group_id_groups", "groups", ["group_id"], ["id"]
        )
        batch_op.drop_column("from_group_id")

    # ### end Alembic commands ###
