"""inbound order id remove unique

Revision ID: 7822ef245f27
Revises: 80e7f5590345
Create Date: 2023-09-01 11:51:41.113665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7822ef245f27'
down_revision = '80e7f5590345'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.drop_constraint('uq_inbound_orders_order_id', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inbound_orders', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_inbound_orders_order_id', ['order_id'])

    # ### end Alembic commands ###
