"""delete office and locker address in user

Revision ID: 7b0bcdf3557f
Revises: c092bf2a51db
Create Date: 2023-06-29 17:40:12.204740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7b0bcdf3557f"
down_revision = "c092bf2a51db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("office_address")
        batch_op.drop_column("locker_address")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "locker_address",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "office_address",
                sa.VARCHAR(length=255),
                autoincrement=False,
                nullable=True,
            )
        )

    # ### end Alembic commands ###
