"""assign

Revision ID: 7c4248d8c529
Revises: accaf952baf1
Create Date: 2023-08-03 23:21:50.686634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c4248d8c529'
down_revision = 'accaf952baf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups_for_product.id'], name=op.f('fk_assigns_group_id_groups_for_product')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_assigns_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assigns'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigns')
    # ### end Alembic commands ###
