"""cart delete group string

Revision ID: 7d28ddd1adfe
Revises: 6278e53df31e
Create Date: 2023-10-02 10:01:22.725777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d28ddd1adfe"
down_revision = "6278e53df31e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.alter_column("group_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.alter_column("group_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
