"""report sku

Revision ID: 7d5021c4714e
Revises: 6278e53df31e
Create Date: 2023-10-03 15:56:40.436810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7d5021c4714e"
down_revision = "6278e53df31e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_skus",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("inbound_order_id", sa.Integer(), nullable=True),
        sa.Column("ship_request_id", sa.Integer(), nullable=True),
        sa.Column("adjustment_id", sa.Integer(), nullable=True),
        sa.Column("assign_id", sa.Integer(), nullable=True),
        sa.Column("share_id", sa.Integer(), nullable=True),
        sa.Column("warehouse_product_id", sa.Integer(), nullable=True),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("qty_before", sa.Integer(), nullable=True),
        sa.Column("qty_after", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["adjustment_id"],
            ["adjusts_group_qty.id"],
            name=op.f("fk_report_skus_adjustment_id_adjusts_group_qty"),
        ),
        sa.ForeignKeyConstraint(
            ["assign_id"], ["assigns.id"], name=op.f("fk_report_skus_assign_id_assigns")
        ),
        sa.ForeignKeyConstraint(
            ["inbound_order_id"],
            ["inbound_orders.id"],
            name=op.f("fk_report_skus_inbound_order_id_inbound_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_report_skus_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["share_id"],
            ["request_share.id"],
            name=op.f("fk_report_skus_share_id_request_share"),
        ),
        sa.ForeignKeyConstraint(
            ["ship_request_id"],
            ["ship_requests.id"],
            name=op.f("fk_report_skus_ship_request_id_ship_requests"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_product_id"],
            ["warehouse_product.id"],
            name=op.f("fk_report_skus_warehouse_product_id_warehouse_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_skus")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("report_skus")
    # ### end Alembic commands ###
