"""Add note_location

Revision ID: 8107ad66cb38
Revises: 8d06b33f1ea4
Create Date: 2024-05-01 12:24:18.604329

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8107ad66cb38"
down_revision = "8d06b33f1ea4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "note_location",
                sa.String(length=512),
                nullable=False,
                server_default="",
            )
        )

    with op.batch_alter_table("products_allocated", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "note_location",
                sa.String(length=512),
                nullable=False,
                server_default="",
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products_allocated", schema=None) as batch_op:
        batch_op.drop_column("note_location")

    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.drop_column("note_location")

    # ### end Alembic commands ###
