"""warehouse product id to report

Revision ID: 82e9943f8142
Revises: 3e28c5a81750
Create Date: 2023-09-25 17:18:31.090671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "82e9943f8142"
down_revision = "3e28c5a81750"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("warehouse_product_id", sa.Integer(), nullable=False)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_report_inventories_warehouse_product_id_warehouse_product"),
            "warehouse_product",
            ["warehouse_product_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_report_inventories_warehouse_product_id_warehouse_product"),
            type_="foreignkey",
        )
        batch_op.drop_column("warehouse_product_id")

    # ### end Alembic commands ###
