"""remove str_values from warehouses

Revision ID: 82efab85f727
Revises: af8e0ca856c9
Create Date: 2023-07-10 17:16:18.981415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82efab85f727'
down_revision = 'af8e0ca856c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_warehouses_country_id_str_values', type_='foreignkey')
        batch_op.drop_constraint('fk_warehouses_region_id_str_values', type_='foreignkey')
        batch_op.drop_column('region_id')
        batch_op.drop_column('country_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('region_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('fk_warehouses_region_id_str_values', 'str_values', ['region_id'], ['id'])
        batch_op.create_foreign_key('fk_warehouses_country_id_str_values', 'str_values', ['country_id'], ['id'])

    # ### end Alembic commands ###
