"""package info added

Revision ID: 86c602aa44db
Revises: 99e9cda02ae8
Create Date: 2023-07-28 17:01:11.310396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "86c602aa44db"
down_revision = "99e9cda02ae8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_info",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("quantity_per_wrap", sa.Integer(), nullable=False),
        sa.Column("quantity_wrap_carton", sa.Integer(), nullable=False),
        sa.Column("quantity_carton_master", sa.Integer(), nullable=False),
        sa.Column("inbound_order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbound_order_id"],
            ["inbound_orders.id"],
            name=op.f("fk_package_info_inbound_order_id_inbound_orders"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_info")),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("package_info")
    # ### end Alembic commands ###
