"""add is_delete for user

Revision ID: 8d06b33f1ea4
Revises: e3163ad16fe6
Create Date: 2024-04-29 16:07:20.333782

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8d06b33f1ea4"
down_revision = "e3163ad16fe6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("is_deleted", sa.Boolean(), nullable=True, server_default="false")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_column("is_deleted")

    # ### end Alembic commands ###
