"""user_group_as_foreign_key

Revision ID: 8e189fc3c68e
Revises: 6de366a1c32e
Create Date: 2023-06-28 21:21:30.600544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e189fc3c68e'
down_revision = '6de366a1c32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_users_group_id_groups'), 'groups', ['group_id'], ['id'])
        batch_op.drop_column('group')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_users_group_id_groups'), type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
