"""supplier edit

Revision ID: 8eceea58c0ac
Revises: afa81825eff5
Create Date: 2023-07-17 16:21:31.749378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8eceea58c0ac"
down_revision = "afa81825eff5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.add_column(sa.Column("contact_number", sa.String(length=64)))
        batch_op.add_column(sa.Column("country", sa.String(length=64)))
        batch_op.add_column(sa.Column("region", sa.String(length=64)))
        batch_op.drop_column("contact_numb")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("suppliers", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "contact_numb",
                sa.VARCHAR(length=64),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("region")
        batch_op.drop_column("country")
        batch_op.drop_column("contact_number")

    # ### end Alembic commands ###
