"""finished date to share request

Revision ID: 901749b97d51
Revises: df2c1fb9efcf
Create Date: 2023-08-25 11:42:01.434264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "901749b97d51"
down_revision = "df2c1fb9efcf"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.add_column(sa.Column("finished_date", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.drop_column("finished_date")

    # ### end Alembic commands ###
