"""assign group from

Revision ID: 917f8437d711
Revises: 4a921e625966
Create Date: 2023-09-16 14:39:54.434165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "917f8437d711"
down_revision = "fde3bec3d9b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.add_column(sa.Column("from_group_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_assigns_from_group_id_groups"),
            "groups",
            ["from_group_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_assigns_from_group_id_groups"), type_="foreignkey"
        )
        batch_op.drop_column("from_group_id")

    # ### end Alembic commands ###
