"""report sku adjust to adjusy qty

Revision ID: 975158512966
Revises: 943a9c8ca92f
Create Date: 2023-10-02 17:02:24.659900

"""
from alembic import op


# revision identifiers, used by Alembic.
revision = "975158512966"
down_revision = "943a9c8ca92f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("report_skus", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_report_skus_adjustment_id_adjusts", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_report_skus_adjustment_id_adjusts_group_qty"),
            "adjusts_group_qty",
            ["adjustment_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_skus", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_report_skus_adjustment_id_adjusts_group_qty"),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_report_skus_adjustment_id_adjusts", "adjusts", ["adjustment_id"], ["id"]
        )

    # ### end Alembic commands ###
