"""remove product from inbound order model

Revision ID: 99e9cda02ae8
Revises: 160fab5d3ecd
Create Date: 2023-07-28 13:31:16.587802

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "99e9cda02ae8"
down_revision = "160fab5d3ecd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.drop_constraint(
            "fk_inbound_orders_product_id_products", type_="foreignkey"
        )
        batch_op.drop_column("product_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("product_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.create_foreign_key(
            "fk_inbound_orders_product_id_products", "products", ["product_id"], ["id"]
        )

    # ### end Alembic commands ###
