"""images table

Revision ID: 9c3b30484072
Revises: 354164e2ae07
Create Date: 2023-10-09 12:50:38.257291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9c3b30484072"
down_revision = "354164e2ae07"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "images",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("path", sa.String(length=256), nullable=False),
        sa.Column("extension", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_images")),
        sa.UniqueConstraint("name", name=op.f("uq_images_name")),
    )
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("image_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_products_image_id_images"), "images", ["image_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_products_image_id_images"), type_="foreignkey"
        )
        batch_op.drop_column("image_id")

    op.drop_table("images")
    # ### end Alembic commands ###
