"""report inventory

Revision ID: 9f27cfb15648
Revises: da43a9878d8e
Create Date: 2023-09-27 17:00:46.948146

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "9f27cfb15648"
down_revision = "da43a9878d8e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_inventory_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_report_inventory_lists_store_id_stores"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_inventory_lists_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_report_inventory_lists_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_inventory_lists")),
    )
    op.create_table(
        "report_inventories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("report_inventory_list_id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_product_id", sa.Integer(), nullable=False),
        sa.Column("qty_before", sa.Integer(), nullable=False),
        sa.Column("qty_after", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_report_inventories_product_id_products"),
        ),
        sa.ForeignKeyConstraint(
            ["report_inventory_list_id"],
            ["report_inventory_lists.id"],
            name=op.f(
                "fk_report_inventories_report_inventory_list_id_report_inventory_lists"
            ),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_product_id"],
            ["warehouse_product.id"],
            name=op.f("fk_report_inventories_warehouse_product_id_warehouse_product"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_inventories")),
    )

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_list_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_inbound_orders_report_inventory_list_id_report_inventory_lists"
            ),
            "report_inventory_lists",
            ["report_inventory_list_id"],
            ["id"],
        )

    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_list_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_ship_requests_report_inventory_list_id_report_inventory_lists"
            ),
            "report_inventory_lists",
            ["report_inventory_list_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_ship_requests_report_inventory_list_id_report_inventory_lists"
            ),
            type_="foreignkey",
        )
        batch_op.drop_column("report_inventory_list_id")

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f(
                "fk_inbound_orders_report_inventory_list_id_report_inventory_lists"
            ),
            type_="foreignkey",
        )
        batch_op.drop_column("report_inventory_list_id")

    op.drop_table("report_inventories")
    op.drop_table("report_inventory_lists")
    # ### end Alembic commands ###
