"""excluded_from_global_increase

Revision ID: a437544ce528
Revises: 1d55a71358e9
Create Date: 2024-12-05 02:24:54.582356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a437544ce528'
down_revision = '1d55a71358e9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billable_groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('excluded_from_global_increase', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billable_groups', schema=None) as batch_op:
        batch_op.drop_column('excluded_from_global_increase')

    # ### end Alembic commands ###
