"""report events stores

Revision ID: a4a1bb2987ff
Revises: e81b0028c2a9
Create Date: 2023-09-20 18:08:22.239449

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a4a1bb2987ff"
down_revision = "e81b0028c2a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_report_events_store_id_stores"),
            "stores",
            ["store_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_events", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_report_events_store_id_stores"), type_="foreignkey"
        )
        batch_op.drop_column("store_id")

    # ### end Alembic commands ###
