"""add reserve date for events

Revision ID: a82982d1dc28
Revises: 917f8437d711
Create Date: 2023-09-18 15:16:48.349180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a82982d1dc28"
down_revision = "917f8437d711"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("date_reserve_from", sa.Date(), nullable=True))
        batch_op.add_column(sa.Column("date_reserve_to", sa.Date(), nullable=True))

    with op.batch_alter_table("package_info", schema=None) as batch_op:
        batch_op.alter_column(
            "quantity_carton_master", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("package_info", schema=None) as batch_op:
        batch_op.alter_column(
            "quantity_carton_master", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_column("date_reserve_to")
        batch_op.drop_column("date_reserve_from")

    # ### end Alembic commands ###
