"""add store category foreign key to ship-request

Revision ID: ab2e0f8ae3a8
Revises: b4a77bf1c442
Create Date: 2023-08-16 10:52:09.718910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab2e0f8ae3a8"
down_revision = "b4a77bf1c442"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(sa.Column("store_category_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_ship_requests_store_category_id_store_categories"),
            "store_categories",
            ["store_category_id"],
            ["id"],
        )
        batch_op.drop_column("store_category")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "store_category",
                sa.VARCHAR(length=64),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_ship_requests_store_category_id_store_categories"),
            type_="foreignkey",
        )
        batch_op.drop_column("store_category_id")

    # ### end Alembic commands ###
