"""report inbound order history length

Revision ID: ad231b84dcd3
Revises: 319a6abd775c
Create Date: 2023-09-29 08:55:31.459329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ad231b84dcd3"
down_revision = "319a6abd775c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_inbound_orders", schema=None) as batch_op:
        batch_op.alter_column(
            "history",
            existing_type=sa.VARCHAR(length=256),
            type_=sa.Text(),
            existing_nullable=True,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("report_inbound_orders", schema=None) as batch_op:
        batch_op.alter_column(
            "history",
            existing_type=sa.Text(),
            type_=sa.VARCHAR(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
