"""add sales_rep, locker_address to user

Revision ID: afa3bb1fe9f7
Revises: 460321884c7d
Create Date: 2023-06-28 12:10:38.244375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa3bb1fe9f7'
down_revision = '460321884c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sales_rep', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('locker_address', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('locker_address')
        batch_op.drop_column('sales_rep')

    # ### end Alembic commands ###
