"""delivery agent add fields

Revision ID: afa81825eff5
Revises: 36d4ddd0b591
Create Date: 2023-07-14 17:56:55.022131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afa81825eff5'
down_revision = '36d4ddd0b591'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agents', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contact_number', sa.String(length=64), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.String(length=64), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('delivery_agents', schema=None) as batch_op:
        batch_op.drop_column('street_address')
        batch_op.drop_column('contact_number')

    # ### end Alembic commands ###
