"""update_store

Revision ID: b0df3d8e5add
Revises: f0349cacb5be
Create Date: 2024-04-19 16:34:18.759545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0df3d8e5add'
down_revision = 'f0349cacb5be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint('uq_stores_store_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_stores_store_name', ['store_name'])

    # ### end Alembic commands ###
