"""add sub group

Revision ID: b1e65c4bb543
Revises: 71314055728b
Create Date: 2024-01-10 15:45:33.495985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e65c4bb543'
down_revision = '71314055728b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.add_column(sa.Column('parent_group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_groups_parent_group_id_groups'), 'groups', ['parent_group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('groups', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_groups_parent_group_id_groups'), type_='foreignkey')
        batch_op.drop_column('parent_group_id')

    # ### end Alembic commands ###
