"""longer name for image

Revision ID: b438f851e9af
Revises: 9c3b30484072
Create Date: 2023-10-10 18:15:16.823779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b438f851e9af"
down_revision = "9c3b30484072"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.VARCHAR(length=128),
            type_=sa.String(length=256),
            existing_nullable=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("images", schema=None) as batch_op:
        batch_op.alter_column(
            "name",
            existing_type=sa.String(length=256),
            type_=sa.VARCHAR(length=128),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
