"""remove warehouse from ship-request, add warehouse to cart

Revision ID: b4a77bf1c442
Revises: bbaac3252c56
Create Date: 2023-08-15 16:22:06.252633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b4a77bf1c442'
down_revision = 'bbaac3252c56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_carts_warehouse_id_warehouses'), 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('product_group', schema=None) as batch_op:
        batch_op.drop_constraint('fk_product_group_group_id_groups', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_group_group_id_groups_for_product'), 'groups_for_product', ['group_id'], ['id'])

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.drop_constraint('fk_ship_requests_warehouse_id_warehouses', type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('fk_ship_requests_warehouse_id_warehouses', 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('product_group', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_product_group_group_id_groups_for_product'), type_='foreignkey')
        batch_op.create_foreign_key('fk_product_group_group_id_groups', 'groups', ['group_id'], ['id'])

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_carts_warehouse_id_warehouses'), type_='foreignkey')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
