"""add extra filed

Revision ID: b649899cbad3
Revises: 576120fad5b3
Create Date: 2024-10-01 13:59:57.517989

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b649899cbad3"
down_revision = "576120fad5b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("incoming_stock_notifications", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "carrier", sa.String(length=128), nullable=False, server_default=""
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("incoming_stock_notifications", schema=None) as batch_op:
        batch_op.drop_column("carrier")

    # ### end Alembic commands ###
