"""quantity added to ship request

Revision ID: b6adac617374
Revises: 4a25e6bf9177
Create Date: 2023-07-18 15:58:38.800225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6adac617374'
down_revision = '4a25e6bf9177'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
