"""user group as foreign key

Revision ID: bc5f276b87a8
Revises: 460321884c7d
Create Date: 2023-06-28 12:46:04.354016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc5f276b87a8"
down_revision = "460321884c7d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_users_group_id_groups"), "groups", ["group_id"], ["id"]
        )
        batch_op.drop_column("group")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "group", sa.VARCHAR(length=255), autoincrement=False, nullable=False
            )
        )
        batch_op.drop_constraint(
            batch_op.f("fk_users_group_id_groups"), type_="foreignkey"
        )
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
