"""event add group

Revision ID: bc88b275bf56
Revises: b438f851e9af
Create Date: 2023-10-13 16:58:51.739430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bc88b275bf56"
down_revision = "b438f851e9af"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(sa.Column("group_id", sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            batch_op.f("fk_events_group_id_groups"), "groups", ["group_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_events_group_id_groups"), type_="foreignkey"
        )
        batch_op.drop_column("group_id")

    # ### end Alembic commands ###
