"""relate package info and product quantity group

Revision ID: c03d756bf5ff
Revises: 236f3a15a64e
Create Date: 2023-09-11 14:56:45.374505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c03d756bf5ff'
down_revision = '236f3a15a64e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_quantity_group_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_package_info_inbound_order_id_inbound_orders', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_package_info_product_quantity_group_id_product_quantity_group'), 'product_quantity_group', ['product_quantity_group_id'], ['id'])
        batch_op.drop_column('inbound_order_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('package_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inbound_order_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_package_info_product_quantity_group_id_product_quantity_group'), type_='foreignkey')
        batch_op.create_foreign_key('fk_package_info_inbound_order_id_inbound_orders', 'inbound_orders', ['inbound_order_id'], ['id'])
        batch_op.drop_column('product_quantity_group_id')

    # ### end Alembic commands ###
