"""user foreign key to store

Revision ID: c2b418abcde8
Revises: 453643ac6064
Create Date: 2023-08-18 17:49:40.018756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c2b418abcde8'
down_revision = '453643ac6064'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('io_allocate_product', schema=None) as batch_op:
        batch_op.alter_column('shelf_life_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('shelf_life_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.alter_column('store_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_stores_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_stores_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.alter_column('store_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('io_allocate_product', schema=None) as batch_op:
        batch_op.alter_column('shelf_life_end',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('shelf_life_start',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    # ### end Alembic commands ###
