"""update RequestShareUser

Revision ID: c35dbdccc45e
Revises: 2f7a756b0fb1
Create Date: 2024-04-25 12:52:16.642638

"""

from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c35dbdccc45e"
down_revision = "2f7a756b0fb1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share_user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reviewed_datetime",
                sa.DateTime(),
                nullable=False,
                server_default=str(datetime.max),
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share_user", schema=None) as batch_op:
        batch_op.drop_column("reviewed_datetime")

    # ### end Alembic commands ###
