"""add user to share request

Revision ID: cb18357a1455
Revises: a82982d1dc28
Create Date: 2023-09-19 10:17:45.131394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cb18357a1455"
down_revision = "a82982d1dc28"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("report_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_request_share_user_id_users"), "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("request_share", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_request_share_user_id_users"), type_="foreignkey"
        )
        batch_op.drop_column("user_id")

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.alter_column("report_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###
