"""rename column role-name division

Revision ID: cd6ddb063574
Revises: 643909f6d74a
Create Date: 2023-07-31 16:07:59.614138

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd6ddb063574'
down_revision = '643909f6d74a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role_name', sa.String(length=64), nullable=False))
        batch_op.drop_constraint('uq_divisions_name', type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_divisions_role_name'), ['role_name'])
        batch_op.drop_column('name')

    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warehouses', schema=None) as batch_op:
        batch_op.alter_column('manager_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('uq_divisions_role_name'), type_='unique')
        batch_op.create_unique_constraint('uq_divisions_name', ['name'])
        batch_op.drop_column('role_name')

    # ### end Alembic commands ###
