"""report inventory

Revision ID: cdfe9a60b29b
Revises: 479bf4cc0532
Create Date: 2023-09-22 14:52:00.390961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdfe9a60b29b"
down_revision = "479bf4cc0532"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_inventories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("qty_before", sa.Integer(), nullable=False),
        sa.Column("qty_after", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_report_inventories_store_id_stores"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_report_inventories_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_report_inventories_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_inventories")),
    )

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_inbound_orders_report_inventory_id_report_inventories"),
            "report_inventories",
            ["report_inventory_id"],
            ["id"],
        )

    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_ship_requests_report_inventory_id_report_inventories"),
            "report_inventories",
            ["report_inventory_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_ship_requests_report_inventory_id_report_inventories"),
            type_="foreignkey",
        )
        batch_op.drop_column("report_inventory_id")

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_inbound_orders_report_inventory_id_report_inventories"),
            type_="foreignkey",
        )
        batch_op.drop_column("report_inventory_id")

    with op.batch_alter_table("assigns", schema=None) as batch_op:
        batch_op.alter_column(
            "from_group_id", existing_type=sa.INTEGER(), nullable=True
        )

    op.drop_table("report_inventories")
    # ### end Alembic commands ###
