"""add ship request notification

Revision ID: ce6e1717944a
Revises: c35dbdccc45e
Create Date: 2024-04-26 11:04:42.431783

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce6e1717944a'
down_revision = 'c35dbdccc45e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_request_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ship_request_id', sa.Integer(), nullable=False),
    sa.Column('reviewed_datetime', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ship_request_id'], ['ship_requests.id'], name=op.f('fk_ship_request_notifications_ship_request_id_ship_requests')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_ship_request_notifications_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ship_request_notifications'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship_request_notifications')
    # ### end Alembic commands ###
