"""wm and da notes to inbound order

Revision ID: cea2e3a205eb
Revises: 8bf135cbedb5
Create Date: 2023-09-13 12:09:32.222309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cea2e3a205eb"
down_revision = "8bf135cbedb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(sa.Column("wm_notes", sa.Text(), nullable=True))
        batch_op.add_column(sa.Column("da_notes", sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("events", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.create_foreign_key(
            "fk_events_user_id_users", "users", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
