"""io_allocate_product

Revision ID: d2fc80a195e3
Revises: f29d82cee24f
Create Date: 2023-08-09 17:37:00.958909

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "d2fc80a195e3"
down_revision = "f29d82cee24f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "io_allocate_product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("inbound_order_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["inbound_order_id"],
            ["inbound_orders.id"],
            name=op.f("fk_io_allocate_product_inbound_order_id_inbound_orders"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_io_allocate_product_product_id_products"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_io_allocate_product")),
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_table("io_allocate_product")
    # ### end Alembic commands ###
