"""Product quantity groups

Revision ID: d3c42bba34e4
Revises: 17a0288bd761
Create Date: 2023-09-05 16:27:34.636756

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd3c42bba34e4'
down_revision = '17a0288bd761'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_quantity_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_allocated_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('fk_product_quantity_group_inbound_order_id_inbound_orders', type_='foreignkey')
        batch_op.drop_constraint('fk_product_quantity_group_product_id_products', type_='foreignkey')
        batch_op.drop_constraint('fk_product_quantity_group_warehouse_id_warehouses', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_product_quantity_group_product_allocated_id_products_allocated'), 'products_allocated', ['product_allocated_id'], ['id'])
        batch_op.drop_column('inbound_order_id')
        batch_op.drop_column('shelf_life_start')
        batch_op.drop_column('shelf_life_end')
        batch_op.drop_column('warehouse_id')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_quantity_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('warehouse_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shelf_life_end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('shelf_life_start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('inbound_order_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(batch_op.f('fk_product_quantity_group_product_allocated_id_products_allocated'), type_='foreignkey')
        batch_op.create_foreign_key('fk_product_quantity_group_warehouse_id_warehouses', 'warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key('fk_product_quantity_group_product_id_products', 'products', ['product_id'], ['id'])
        batch_op.create_foreign_key('fk_product_quantity_group_inbound_order_id_inbound_orders', 'inbound_orders', ['inbound_order_id'], ['id'])
        batch_op.drop_column('product_allocated_id')

    # ### end Alembic commands ###
