"""ship_request_billable

Revision ID: d45b8a7bbecf
Revises: 389030ed9b77
Create Date: 2024-11-29 07:17:59.134287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd45b8a7bbecf'
down_revision = '389030ed9b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ship_request_billables',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billable_group_id', sa.Integer(), nullable=True),
    sa.Column('ship_request_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('incoming', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['billable_group_id'], ['billable_groups.id'], name=op.f('fk_ship_request_billables_billable_group_id_billable_groups'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ship_request_id'], ['ship_requests.id'], name=op.f('fk_ship_request_billables_ship_request_id_ship_requests'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ship_request_billables'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ship_request_billables')
    # ### end Alembic commands ###
