"""add expiry_date

Revision ID: d87c04071595
Revises: 28e2d7f74bc1
Create Date: 2024-05-17 14:34:10.230055

"""

from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d87c04071595"
down_revision = "28e2d7f74bc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.alter_column(
            "from_warehouse_product_id", existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "expiry_date",
                sa.DateTime(),
                nullable=False,
                server_default=str(datetime.max),
            )
        )
        batch_op.drop_column("expire_date")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "expire_date",
                sa.VARCHAR(),
                server_default=sa.text("'N/A'::character varying"),
                autoincrement=False,
                nullable=False,
            )
        )
        batch_op.drop_column("expiry_date")

    with op.batch_alter_table("carts", schema=None) as batch_op:
        batch_op.alter_column(
            "from_warehouse_product_id", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###
