"""remove comment cart add comment ship_request

Revision ID: d9389bd518f4
Revises: f0ed949ce9d2
Create Date: 2023-07-24 09:28:04.793731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9389bd518f4'
down_revision = 'f0ed949ce9d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.drop_column('comments')

    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment', sa.String(length=256)))
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.alter_column('store_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('warehouse_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('comment')

    with op.batch_alter_table('carts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comments', sa.VARCHAR(length=256), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
