"""report inbound order

Revision ID: da43a9878d8e
Revises: a919bd570a83
Create Date: 2023-09-27 15:57:03.243262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "da43a9878d8e"
down_revision = "a919bd570a83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_inbound_orders",
        sa.Column("id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("inbound_order_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=True),
        sa.Column("history", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["inbound_order_id"],
            ["inbound_orders.id"],
            name=op.f("fk_report_inbound_orders_inbound_order_id_inbound_orders"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_inbound_orders_user_id_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_inbound_orders")),
    )
    with op.batch_alter_table("adjusts", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("adjusts_group_qty", schema=None) as batch_op:
        batch_op.alter_column("product_id", existing_type=sa.INTEGER(), nullable=True)
        batch_op.alter_column(
            "quantity_after", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "quantity_before", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adjusts_group_qty", schema=None) as batch_op:
        batch_op.alter_column(
            "quantity_before", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column(
            "quantity_after", existing_type=sa.INTEGER(), nullable=True
        )
        batch_op.alter_column("product_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("adjusts", schema=None) as batch_op:
        batch_op.alter_column("user_id", existing_type=sa.INTEGER(), nullable=True)

    op.drop_table("report_inbound_orders")
    # ### end Alembic commands ###
