"""warehouse product to report inventory

Revision ID: dad63a7b1bc4
Revises: cdfe9a60b29b
Create Date: 2023-09-25 11:05:58.277084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dad63a7b1bc4"
down_revision = "cdfe9a60b29b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_warehouse_product_report_inventory_id_report_inventories"),
            "report_inventories",
            ["report_inventory_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouse_product", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_warehouse_product_report_inventory_id_report_inventories"),
            type_="foreignkey",
        )
        batch_op.drop_column("report_inventory_id")

    # ### end Alembic commands ###
