"""add warehouse id to adjusts_group_qty

Revision ID: ddb8f80bcc80
Revises: 2d0e8d6473a9
Create Date: 2023-08-28 15:46:50.502696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ddb8f80bcc80"
down_revision = "2d0e8d6473a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adjusts_group_qty", schema=None) as batch_op:
        batch_op.add_column(sa.Column("warehouse_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_adjusts_group_qty_warehouse_id_warehouses"),
            "warehouses",
            ["warehouse_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("adjusts_group_qty", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_adjusts_group_qty_warehouse_id_warehouses"),
            type_="foreignkey",
        )
        batch_op.drop_column("warehouse_id")

    # ### end Alembic commands ###
