"""add request share table

Revision ID: dee7621445a9
Revises: 22393992ca51
Create Date: 2023-08-02 10:39:36.668906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "dee7621445a9"
down_revision = "22393992ca51"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "request_share",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("group_id", sa.Integer(), nullable=False),
        sa.Column("desire_quantity", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["group_id"], ["groups.id"], name=op.f("fk_request_share_group_id_groups")
        ),
        sa.ForeignKeyConstraint(
            ["product_id"],
            ["products.id"],
            name=op.f("fk_request_share_product_id_products"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_share")),
    )
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.alter_column("manager_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("warehouses", schema=None) as batch_op:
        batch_op.alter_column("manager_id", existing_type=sa.INTEGER(), nullable=True)

    op.drop_table("request_share")
    # ### end Alembic commands ###
