"""add expire_date

Revision ID: e3163ad16fe6
Revises: ce6e1717944a
Create Date: 2024-04-29 11:22:52.542823

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e3163ad16fe6"
down_revision = "ce6e1717944a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("expire_date", sa.String(), nullable=False, server_default="N/A")
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("expire_date")

    # ### end Alembic commands ###
