"""add create-at to request-share

Revision ID: e5ae3950b1a2
Revises: 2cb65e4339a6
Create Date: 2023-08-02 15:26:01.164375

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5ae3950b1a2'
down_revision = '2cb65e4339a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
