"""Report events

Revision ID: e81b0028c2a9
Revises: cb18357a1455
Create Date: 2023-09-19 14:35:26.442545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81b0028c2a9'
down_revision = 'cb18357a1455'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigns', schema=None) as batch_op:
        batch_op.alter_column('from_group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request_share', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('report_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('assigns', schema=None) as batch_op:
        batch_op.alter_column('from_group_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
