"""report inventory list

Revision ID: e8614135c5ff
Revises: dad63a7b1bc4
Create Date: 2023-09-25 12:01:33.904740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e8614135c5ff"
down_revision = "dad63a7b1bc4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "report_inventory_lists",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("warehouse_id", sa.Integer(), nullable=True),
        sa.Column("store_id", sa.Integer(), nullable=True),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["store_id"],
            ["stores.id"],
            name=op.f("fk_report_inventory_lists_store_id_stores"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_report_inventory_lists_user_id_users"),
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_report_inventory_lists_warehouse_id_warehouses"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_inventory_lists")),
    )

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_list_id", sa.Integer(), nullable=True)
        )
        batch_op.drop_constraint(
            "fk_inbound_orders_report_inventory_id_report_inventories",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_inbound_orders_report_inventory_list_id_report_inventory_lists"
            ),
            "report_inventory_lists",
            ["report_inventory_list_id"],
            ["id"],
        )
        batch_op.drop_column("report_inventory_id")

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_list_id", sa.Integer(), nullable=False)
        )
        batch_op.drop_constraint(
            "fk_report_inventories_user_id_users", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_report_inventories_warehouse_id_warehouses", type_="foreignkey"
        )
        batch_op.drop_constraint(
            "fk_report_inventories_store_id_stores", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_report_inventories_report_inventory_list_id_report_inventory_lists"
            ),
            "report_inventory_lists",
            ["report_inventory_list_id"],
            ["id"],
        )
        batch_op.drop_column("warehouse_id")
        batch_op.drop_column("store_id")
        batch_op.drop_column("user_id")
        batch_op.drop_column("type")

    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("report_inventory_list_id", sa.Integer(), nullable=True)
        )
        batch_op.drop_constraint(
            "fk_ship_requests_report_inventory_id_report_inventories",
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            batch_op.f(
                "fk_ship_requests_report_inventory_list_id_report_inventory_lists"
            ),
            "report_inventory_lists",
            ["report_inventory_list_id"],
            ["id"],
        )
        batch_op.drop_column("report_inventory_id")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "report_inventory_id", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_ship_requests_report_inventory_list_id_report_inventory_lists"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_ship_requests_report_inventory_id_report_inventories",
            "report_inventories",
            ["report_inventory_id"],
            ["id"],
        )
        batch_op.drop_column("report_inventory_list_id")

    with op.batch_alter_table("report_inventories", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "type", sa.VARCHAR(length=64), autoincrement=False, nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False)
        )
        batch_op.add_column(
            sa.Column("store_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.add_column(
            sa.Column("warehouse_id", sa.INTEGER(), autoincrement=False, nullable=True)
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_report_inventories_report_inventory_list_id_report_inventory_lists"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_report_inventories_store_id_stores", "stores", ["store_id"], ["id"]
        )
        batch_op.create_foreign_key(
            "fk_report_inventories_warehouse_id_warehouses",
            "warehouses",
            ["warehouse_id"],
            ["id"],
        )
        batch_op.create_foreign_key(
            "fk_report_inventories_user_id_users", "users", ["user_id"], ["id"]
        )
        batch_op.drop_column("report_inventory_list_id")

    with op.batch_alter_table("inbound_orders", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "report_inventory_id", sa.INTEGER(), autoincrement=False, nullable=True
            )
        )
        batch_op.drop_constraint(
            batch_op.f(
                "fk_inbound_orders_report_inventory_list_id_report_inventory_lists"
            ),
            type_="foreignkey",
        )
        batch_op.create_foreign_key(
            "fk_inbound_orders_report_inventory_id_report_inventories",
            "report_inventories",
            ["report_inventory_id"],
            ["id"],
        )
        batch_op.drop_column("report_inventory_list_id")

    op.drop_table("report_inventory_lists")
    # ### end Alembic commands ###
