"""event add group

Revision ID: ed00960cfc58
Revises: 9c3b30484072
Create Date: 2023-10-11 14:10:26.242316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed00960cfc58'
down_revision = '9c3b30484072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_events_group_id_groups'), 'groups', ['group_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_events_group_id_groups'), type_='foreignkey')
        batch_op.drop_column('group_id')

    # ### end Alembic commands ###
