"""add label_role_name

Revision ID: f0349cacb5be
Revises: 4f67bc90cf20
Create Date: 2024-04-03 17:24:50.358192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0349cacb5be'
down_revision = '4f67bc90cf20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label_role_name', sa.String(length=64), nullable=True))
        batch_op.drop_constraint('uq_divisions_role_name', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('divisions', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_divisions_role_name', ['role_name'])
        batch_op.drop_column('label_role_name')

    # ### end Alembic commands ###
