"""store and warehouse to ship request

Revision ID: f0ed949ce9d2
Revises: aeb049f8c659
Create Date: 2023-07-21 12:43:04.703688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0ed949ce9d2'
down_revision = 'aeb049f8c659'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('warehouse_id', sa.Integer()))
        batch_op.add_column(sa.Column('store_id', sa.Integer()))
        batch_op.drop_constraint('fk_ship_requests_supplier_id_suppliers', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_ship_requests_warehouse_id_warehouses'), 'warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_ship_requests_store_id_stores'), 'stores', ['store_id'], ['id'])
        batch_op.drop_column('supplier_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ship_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supplier_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_ship_requests_store_id_stores'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_ship_requests_warehouse_id_warehouses'), type_='foreignkey')
        batch_op.create_foreign_key('fk_ship_requests_supplier_id_suppliers', 'suppliers', ['supplier_id'], ['id'])
        batch_op.drop_column('store_id')
        batch_op.drop_column('warehouse_id')

    # ### end Alembic commands ###
