"""nullable warehouse_id for ship request

Revision ID: f512256a42d1
Revises: 3a1d4b6d3019
Create Date: 2023-07-26 15:44:15.415709

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f512256a42d1"
down_revision = "3a1d4b6d3019"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.alter_column("warehouse_id", existing_type=sa.INTEGER(), nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ship_requests", schema=None) as batch_op:
        batch_op.alter_column(
            "warehouse_id", existing_type=sa.INTEGER(), nullable=False
        )

    # ### end Alembic commands ###
