"""one to one package info and product quantity group

Revision ID: fa5a2d5129c0
Revises: c03d756bf5ff
Create Date: 2023-09-12 09:39:04.944751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fa5a2d5129c0"
down_revision = "c03d756bf5ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.add_column(sa.Column("package_info_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_product_quantity_group_package_info_id_package_info"),
            "package_info",
            ["package_info_id"],
            ["id"],
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("product_quantity_group", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_product_quantity_group_package_info_id_package_info"),
            type_="foreignkey",
        )
        batch_op.drop_column("package_info_id")

    # ### end Alembic commands ###
