"""single price for product

Revision ID: fb49efe5fbdb
Revises: f29d82cee24f
Create Date: 2023-08-11 10:27:09.710723

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = "fb49efe5fbdb"
down_revision = "f29d82cee24f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(sa.Column("price", sa.Float(), nullable=True))
        batch_op.drop_column("retail_price")
        batch_op.drop_column("regular_price")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "regular_price",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "retail_price",
                sa.DOUBLE_PRECISION(precision=53),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_column("price")

    # ### end Alembic commands ###
