declare const priceElements: NodeListOf<Element>;
declare const quantityElements: NodeListOf<Element>;
declare const totalPriceElement: Element;
declare const totalQuantityElement: Element;
declare const tableCartItems: NodeListOf<Element>;
declare function countTotalsPriceQuantity(): void;
declare const deliverToStoreBtn: Element;
declare const createStoreRequestContainer: HTMLDivElement;
declare const deleteButtons: NodeListOf<Element>;
